// examples/react/src/main.tsx
import { DialexProvider } from "dialexjs/react";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import App from "./App.tsx";

import "./index.css";
import { dialex } from "./dialex.generated";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <DialexProvider {...dialex}>
      <App />
    </DialexProvider>
  </StrictMode>,
);

// examples/solid/src/index.tsx
/* @refresh reload */
import { DialexProvider } from "dialexjs/solid";
import { render } from "solid-js/web";

import App from "./App.tsx";
import { dialex } from "./dialex.generated";

import "./index.css";

render(
  () => (
    <DialexProvider {...dialex}>
      <App />
    </DialexProvider>
  ),
  document.getElementById("root")!,
);
